const markerConstants = {
  MARKER_SMALL: '1.5rem',
  MARKER_BIG: '4rem',
  MARKER_SMALL_CORR: 8,
  MARKER_BIG_CORR: 20,

  CIRCLE_SMALL_SIDES: '1rem',
  CIRCLE_MEDIUM_SIDES: '2rem',
  CIRCLE_LARGE_SIDES: '5rem',

  CIRCLE_SMALL_FR_REAR: '1.2rem',
  CIRCLE_MEDIUM_FR_REAR: '2.4rem',
  CIRCLE_LARGE_FR_REAR: '5rem',

  CIRCLE_SMALL_X_CORR: 6.5,
  CIRCLE_SMALL_Y_CORR: 6,
  CIRCLE_MEDIUM_X_CORR: 12.5,
  CIRCLE_MEDIUM_Y_CORR: 12.5,
  CIRCLE_LARGE_X_CORR: 25,
  CIRCLE_LARGE_Y_CORR: 25,

  IMAGE_WIDTH_SIDE: '1000px',
  IMAGE_WIDTH_FR_REAR: '500px',

  LINE_SMALL_W: '1.2rem',
  LINE_SMALL_H: '0.6rem',
  LINE_MEDIUM_W: '2.4rem',
  LINE_MEDIUM_H: '1rem',
  LINE_LARGE_W: '5rem',
  LINE_LARGE_H: '1.5rem',
  LINE_SMALL_X_CORR: 6.5,
  LINE_SMALL_Y_CORR: 4,
  LINE_MEDIUM_X_CORR: 12.5,
  LINE_MEDIUM_Y_CORR: 6,
  LINE_LARGE_X_CORR: 25,
  LINE_LARGE_Y_CORR: 8,

  UPLOADED_IMAGE_WIDTH: '1000px',
};

module.exports = markerConstants;
